export const REQUEST_ITEMS = 'HOME_REQUEST_ITEMS';
export const RECEIVE_ITEMS = 'HOME_RECEIVE_ITEMS';
export const FAIL_ITEMS = 'HOME_FAIL_ITEMS';
export const SEARCH_CHANGED = 'HOME_SEARCH_CHANGED';
export const LOAD_SOME = 'HOME_LOAD_SOME';

export default {
	REQUEST_ITEMS,
	RECEIVE_ITEMS,
	FAIL_ITEMS,
	SEARCH_CHANGED,
	LOAD_SOME
};